CXX      := g++
CXXFLAGS := -std=c++17 -O2 -Wall -Wextra -Iinclude

# SFML (ajuste se necessário)
SFML_DIR := C:/SFML-3.0.2
SFML_INC := -I$(SFML_DIR)/include
SFML_LIBDIR := -L$(SFML_DIR)/lib
LDLIBS_SFML := -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio -lws2_32

LDFLAGS_DEBUG := -mconsole
LDFLAGS_GAME := -mwindows

BUILD_DIR := build
BUILD_OBJ_DIR := $(BUILD_DIR)/obj
EXE_GAME := bin/game.exe
EXE_DEBUG := bin/debug.exe

SRC_SFML := \
	src/main.cpp \
	src/WindowManager.cpp \
	src/Game.cpp \
	src/Multiplayer.cpp \
	src/table.cpp \
	src/net_client.cpp \
	src/server.cpp \
	src/SinglePlayerState.cpp

OBJ_SFML := $(addprefix $(BUILD_OBJ_DIR)/,$(notdir $(SRC_SFML:.cpp=.o)))


.PHONY: all game debug clean

all: game debug

game: $(EXE_GAME)

debug: $(EXE_DEBUG)

$(BUILD_DIR):
	@mkdir -p $(BUILD_DIR)

$(BUILD_OBJ_DIR): | $(BUILD_DIR)
	@mkdir -p $(BUILD_OBJ_DIR)

$(EXE_GAME): $(BUILD_OBJ_DIR) $(OBJ_SFML)
	$(CXX) $(CXXFLAGS) $(OBJ_SFML) -o $@ $(LDFLAGS_GAME) $(SFML_LIBDIR) $(LDLIBS_SFML)

$(EXE_DEBUG): $(BUILD_OBJ_DIR) $(OBJ_SFML)
	$(CXX) $(CXXFLAGS) $(OBJ_SFML) -o $@ $(LDFLAGS_DEBUG) $(SFML_LIBDIR) $(LDLIBS_SFML)

$(BUILD_OBJ_DIR)/%.o: src/%.cpp | $(BUILD_OBJ_DIR)
	$(CXX) $(CXXFLAGS) $(SFML_INC) -c $< -o $@

clean:
	@rm -rf $(BUILD_DIR) $(EXE_GAME) $(EXE_DEBUG)
